apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cached
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cached 
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Pods
        value: 1
        periodSeconds: 1
