apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: timeline
  name: timeline
spec:
  ports:
    - name: "8089"
      port: 8089
      targetPort: 8089
    - name: "5000"
      port: 5000
      targetPort: 5000
    - name: "9999"
      port: 9999
      targetPort: 9999
  selector:
    io.kompose.service: timeline
status:
  loadBalancer: {}
