apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: home
  name: home
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: home
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
        sidecar.istio.io/statsInclusionPrefixes: cluster.outbound,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grp,listener,connection_manager
        sidecar.istio.io/statsInclusionRegexps: http.*
      creationTimestamp: null
      labels:
        io.kompose.service: home
    spec:
      containers:
        - command:
            - home
          image: arielszekely/socialnetworkk8s:latest
          name: socialnetwork-home
          ports:
            - containerPort: 8090
            - containerPort: 5000
            - containerPort: 9999
          resources:
            requests:
              cpu: 1900m
      restartPolicy: Always
status: {}
