apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  storageClassName: mongo-storage
  hostPath:
    path: /data/volumes/mongo-pv   # Where all the hard drives are mounted
    type: DirectoryOrCreate
