apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: cedar 
  name: cedar 
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cedar
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
#        sidecar.istio.io/statsInclusionPrefixes: cluster.outbound,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grp,listener,connection_manager
#        sidecar.istio.io/statsInclusionRegexps: http.*
      creationTimestamp: null
      labels:
        io.kompose.service: cedar
    spec:
      containers:
        - image: permitio/cedar-agent:latest
          name: cedar
          ports:
            - containerPort: 8180
          resources:
            requests:
              cpu: 0m
            limits:
              cpu: 4000m
      restartPolicy: Always
status: {}
