apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: cached
  name: cached
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: cached
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
        sidecar.istio.io/statsInclusionPrefixes: cluster.outbound,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grp,listener,connection_manager
        sidecar.istio.io/statsInclusionRegexps: http.*
      creationTimestamp: null
      labels:
        io.kompose.service: cached
    spec:
      priorityClassName: high-priority
      containers:
        - command:
            - cached
          image: arielszekely/hotelreservation:latest
          name: hotel-reserv-cached
          ports:
            - containerPort: 8091
            - containerPort: 5555
          resources:
            requests:
              cpu: 1900m
            limits:
              cpu: 4000m
          env:
            - name: POD_IP_ADDR
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CACHE_TYPE
              value: "cached"
      restartPolicy: Always
status: {}
