apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: compose
  name: compose
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: compose
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
        sidecar.istio.io/statsInclusionPrefixes: cluster.outbound,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grp,listener,connection_manager
        sidecar.istio.io/statsInclusionRegexps: http.*
      creationTimestamp: null
      labels:
        io.kompose.service: compose
    spec:
      containers:
        - command:
            - compose
          image: arielszekely/socialnetworkk8s:latest
          name: socialnetwork-compose
          ports:
            - containerPort: 8081
            - containerPort: 5000
          resources:
            requests:
              cpu: 950m
      restartPolicy: Always
status: {}
